In [21]:
import numpy as np

# 20 UNIVERSAL FUNC

Universal Functions: Fast Element-wise Array Functions
A universal function, or ufunc, is a function that performs elementwise operations on
data in ndarrays. You can think of them as fast vectorized wrappers for simple functions
that take one or more scalar values and produce one or more scalar results

In [24]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [34]:
arr2 = np.random.randn(7)
print(arr2)
f,w = np.modf(arr2)
print(f,w, sep="\n\n")

[-0.31397061 -0.67506181  0.38652635 -0.36053814 -1.01337558  0.68984369
 -2.00376261]
[-0.31397061 -0.67506181  0.38652635 -0.36053814 -0.01337558  0.68984369
 -0.00376261]

[-0. -0.  0. -0. -1.  0. -2.]


In [38]:
arr3 = np.array([2,3,5,-9])
np.abs(arr3)

array([2, 3, 5, 9])

In [39]:
np.fabs(arr3)

array([2., 3., 5., 9.])

In [40]:
np.square(arr3)

array([ 4,  9, 25, 81], dtype=int32)

In [41]:
np.exp(arr3)

array([7.38905610e+00, 2.00855369e+01, 1.48413159e+02, 1.23409804e-04])

In [45]:
np.sign(arr3)

array([ 1,  1,  1, -1])

In [46]:
arr4 = np.array([2.4,2.5,2.6])
np.ceil(arr4)

array([3., 3., 3.])

In [47]:
np.floor(arr4)

array([2., 2., 2.])

In [50]:
np.isnan(arr3)

array([False, False, False, False])

In [51]:
np.isfinite(arr3)

array([ True,  True,  True,  True])

In [52]:
np.isinf(arr3)

array([False, False, False, False])

In [53]:
np.logical_not(arr3)

array([False, False, False, False])

In [57]:
np.floor_divide(arr3,2)

array([ 1,  1,  2, -5], dtype=int32)

In [62]:
arr5 =np.array([2,3,4,5])
arr6 = np.array([2,3,4,5])

np.power(arr5,arr6)

array([   4,   27,  256, 3125], dtype=int32)

In [63]:
np.fmax(arr5,arr6)

array([2, 3, 4, 5])

In [64]:
np.mod(arr5,arr6)

array([0, 0, 0, 0], dtype=int32)

In [66]:
np.copysign(arr5,arr6)

array([2., 3., 4., 5.])

In [68]:
np.cos(arr5)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [69]:
np.sin(arr5)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [22]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

a+b

array([2, 4, 6, 8])

In [23]:
c = np.arange(3*3).reshape(3,3)
print(c)
print()
print(np.add.reduce(c,1))
print()
print(np.add.reduce(c,(0,1)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[ 3 12 21]

36


In [14]:
a = np.add(5,6)
a

11

In [18]:
a = np.arange(3*3).reshape(3,3)
b = np.arange(3)
print(a)
print()
print(b)
print()
np.add(a,b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2]



array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [19]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.subtract(x1, x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [20]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])