Problem 1

How to import pandas and check the version?

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.5'

Problem 2

Create a pandas series from each of the items below: a list, numpy and a dictionary

Input

```
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```

In [2]:
mylist = list("abcdefghijklmnopqrstuvwxyz")
myarr = np.arange(26)
mydict = dict(zip(mylist,myarr))
mydict
ser = pd.Series(mydict)
ser

a     0
b     1
c     2
d     3
e     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

Problem 3

Convert the series ser into a dataframe with its index as another column on the dataframe.

Input

```
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
```

In [3]:
df = pd.DataFrame(ser).reset_index()
df

index   0
0      a   0
1      b   1
2      c   2
3      d   3
4      e   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [8]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
df = ser.to_frame().reset_index()
df

index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

Problem 4

Combine ser1 and ser2 to form a dataframe.

Input:

```
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
```

In [4]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
df = pd.DataFrame({"col1":ser1,"col2":ser2})
df
pd.concat([ser1,ser2],axis=1)

0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [10]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
df = pd.DataFrame({"S1":ser1,"S2":ser2})
df

pd.concat([ser1,ser2], axis=1)

0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

Problem 5

Get all items of ser1 and ser2 not common to both.

Input

```
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [5]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

union = pd.Series(np.union1d(ser1,ser2))
intersect = pd.Series(np.intersect1d(ser1,ser2))

output = union[~union.isin(intersect)]
output

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

Problem 6

Compute the minimum, 25th percentile, median, 75th, and maximum of ser.

Input

```
ser = pd.Series(np.random.normal(10, 5, 25))

```

In [42]:
ser = pd.Series(np.random.normal(10,5,25))
print("original",ser)
np.percentile(ser,q=[0,25,50,70,100])

original 0     15.042662
1     10.138979
2     15.578486
3      8.541596
4     18.334150
5     11.770068
6     12.017236
7      9.469345
8      9.669044
9      7.361957
10    15.913096
11    16.913969
12     5.152236
13    12.027481
14    13.387411
15    16.187514
16    16.542180
17     5.591258
18    17.163291
19     8.560837
20     6.166906
21     1.912090
22    16.851034
23     7.493756
24    12.969894
dtype: float64


array([ 1.91208954,  8.54159579, 12.01723553, 15.47132122, 18.33414956])

Problem 7

Calculte the frequency counts of each unique value ser.

Input

```
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
```

In [62]:
ser = pd.Series(np.take(list("abcdefgh"), np.random.randint(8, size=20)))
print(ser)
ser.value_counts()

0     h
1     h
2     e
3     a
4     e
5     c
6     e
7     b
8     e
9     a
10    c
11    e
12    e
13    a
14    g
15    f
16    h
17    d
18    g
19    f
dtype: object


e    6
a    3
h    3
g    2
c    2
f    2
b    1
d    1
dtype: int64

Problem 8

From ser, keep the top 2 most frequent items as it is and replace everything else as ‘Other’.

Input

```

np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
```

In [8]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print(ser)

# Solution
print("Top 2 Freq:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
ser

0     4
1     2
2     4
3     2
4     1
5     4
6     4
7     1
8     4
9     2
10    2
11    3
dtype: int32
Top 2 Freq: 4    5
2    4
1    2
3    1
dtype: int64


0         4
1         2
2         4
3         2
4     Other
5         4
6         4
7     Other
8         4
9         2
10        2
11    Other
dtype: object

Problem 9

Bin the series ser into 10 equal deciles and replace the values with the bin name.

Input
```
ser = pd.Series(np.random.random(20))
```
Desired Output

```
# First 5 items
0    7th
1    9th
2    7th
3    3rd
4    8th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]
```

In [10]:
np.random.normal(100)
ser = pd.Series(np.random.random(10))
print(ser)

out = pd.qcut(ser, q=[0,.10,.20,.3,.4,.5,.6,.7,.8,.9,1],
       labels=["first","2nd","third","4th","5th","6th","7th","8th","9th","10th"])

out

0    0.083185
1    0.357671
2    0.378297
3    0.663645
4    0.850919
5    0.148385
6    0.635109
7    0.544050
8    0.097147
9    0.122272
dtype: float64


0    first
1      5th
2      6th
3      9th
4     10th
5      4th
6      8th
7      7th
8      2nd
9    third
dtype: category
Categories (10, object): ['first' < '2nd' < 'third' < '4th' ... '7th' < '8th' < '9th' < '10th']

Problem 10

Reshape the series ser into a dataframe with 7 rows and 5 columns

Input

```
ser = pd.Series(np.random.randint(1, 10, 35))
```

In [13]:
ser = pd.Series(np.random.randint(1,10,35))
ser

df = pd.DataFrame(ser.values.reshape(7,5))
df

0  1  2  3  4
0  6  4  2  6  4
1  6  9  7  6  2
2  5  6  7  6  5
3  7  4  4  6  7
4  3  5  3  8  5
5  1  4  6  2  2
6  6  6  2  5  4

In [5]:
ser = pd.Series(np.random.randint(1,10,35))

df = pd.DataFrame(ser.values.reshape(7,5))
df

0  1  2  3  4
0  3  7  4  2  6
1  6  2  6  9  9
2  5  3  8  8  5
3  1  2  3  5  6
4  5  4  9  5  8
5  3  5  2  4  1
6  1  3  6  4  7

Problem 11 

Find the positions of numbers that are multiples of 3 from ser.

Input

```
ser = pd.Series(np.random.randint(1, 10, 7))
```

In [16]:
arr = np.array(np.random.randint(1,10,7))
print(arr)
np.argwhere(arr%3==0)

[8 5 4 7 3 6 7]


array([[4],
       [5]], dtype=int64)

In [6]:
ser = pd.Series(np.random.randint(1,10,7))
print(ser)
ser[ser%3==0]
new_arr = ser.to_numpy()
type(new_arr)
np.argwhere(new_arr%3 ==0)

0    8
1    1
2    6
3    6
4    3
5    9
6    5
dtype: int32


array([[2],
       [3],
       [4],
       [5]], dtype=int64)

Problem 12

Stack ser1 and ser2 vertically and horizontally (to form a dataframe).

Input

```
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
```

In [20]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list("abcde"))

df = pd.DataFrame({"col1":ser1, "col2":ser2})
df

col1 col2
0     0    a
1     1    b
2     2    c
3     3    d
4     4    e

Problem 13

Stack ser1 and ser2 vertically and horizontally (to form a dataframe).

Input
```
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
```

In [ ]:
df = pd.concat([ser1,ser2], axis=1)
df

Problem 14


Get the day of month, week number, day of year and day of week from ser.

Input
```
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```
Desired output
```
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']
```

In [12]:
import pandas as pd

# create a series of dates
dates = pd.Series(['2022-02-01', '2022-02-05', '2022-03-12', '2022-04-15'])

# convert the series to a pandas datetime format
dates = pd.to_datetime(dates)

# extract the day of the month
day_of_month = dates.dt.day
print("Day of Month:")
print(day_of_month)

# extract the week number
week_number = dates.dt.week
print("\nWeek Number:")
print(week_number)

# extract the day of the year
day_of_year = dates.dt.dayofyear
print("\nDay of Year:")
print(day_of_year)

# extract the day of the week
day_of_week = dates.dt.day_name()
print("\nDay of Week:")
print(day_of_week)


Day of Month:
0     1
1     5
2    12
3    15
dtype: int64

Week Number:
0     5
1     5
2    10
3    15
dtype: int64

Day of Year:
0     32
1     36
2     71
3    105
dtype: int64

Day of Week:
0     Tuesday
1    Saturday
2    Saturday
3      Friday
dtype: object


C:\Users\I-Tech\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  from ipykernel import kernelapp as app


In [13]:
dates = pd.Series(['2022-02-01', '2022-02-05', '2022-03-12', '2022-04-15'])

dates = pd.to_datetime(dates)

dayofmonth = dates.dt.day
print("dayofmonth")
print(dayofmonth)

weeknumber = dates.dt.week
print("weeknum")
print(week_number)

dayofyear = dates.dt.dayofyear
print("dayofyear")
print(dayofyear)

dayname = dates.dt.day_name()
print("dayname")
print(dayname)

dayofmonth
0     1
1     5
2    12
3    15
dtype: int64
weeknum
0     5
1     5
2    10
3    15
dtype: int64
dayofyear
0     32
1     36
2     71
3    105
dtype: int64
dayname
0     Tuesday
1    Saturday
2    Saturday
3      Friday
dtype: object


C:\Users\I-Tech\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  if __name__ == '__main__':


Problem 15

From ser, extract words that contain atleast 2 vowels.

Input
```
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
```

Desired Output
```
0     Apple
1    Orange
4     Money
dtype: object
```

In [101]:
# Define the list of vowels
vowels = ['a', 'e', 'i', 'o', 'u']

# Define the series of words
words = pd.Series(['apple', 'banana', 'cat', 'dog', 'elephant', 'frog', 'giraffe'])

# Define an empty list to store the filtered words
filtered_words = []

# Loop through each word in the series
for word in words:
    # Count the number of vowels in the word
    vowel_count = sum([1 for char in word if char.lower() in vowels])
    # If the count is at least 2, add the word to the filtered_words list
    if vowel_count >= 2:
        filtered_words.append(word)

# Return the filtered_words list
filtered_words


['apple', 'banana', 'elephant', 'giraffe']

Problem 16


Check if df has any missing values.

Input

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.isnull().sum()
df.isnull().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

Problem 17

Count the number of missing values in each column of df. Which column has the maximum number of missing values?

Input
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [51]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
num_of_missing_each_col = df.apply(lambda x: x.isnull().sum())
num_of_missing_each_col.argmax()

23

In [34]:
count_missing_values = df.apply(lambda x: x.isnull().sum())
count_missing_values.idxmax()

'Luggage.room'

Problem 18

Replace missing values in Min.Price and Max.Price columns with their respective mean.

Input

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [50]:
df.columns

df[["Min.Price","Max.Price"]] = df[["Min.Price","Max.Price"]].apply(lambda x: x.fillna(x.mean()))
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

Problem 19

In df, use apply method to replace the missing values in Min.Price with the column’s mean and those in Max.Price with the column’s median.

Input

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

```

In [29]:
df_output = df[["Min.Price","Max.Price"]].apply(lambda x: x.fillna({"Min.Price":df["Min.Price"].mean(),
                                                                   "Max.Price":df["Max.Price"].median()}))
df_output

Min.Price  Max.Price
0        12.9       18.8
1        29.2       38.7
2        25.9       32.3
3         NaN       44.6
4         NaN        NaN
..        ...        ...
88       16.6       22.7
89       17.6       22.4
90       22.9       23.7
91       21.8       23.5
92       24.8       28.5

[93 rows x 2 columns]

Problem 20

Get the first column (a) in df as a dataframe (rather than as a Series).

Input

```
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
```

In [33]:
df = pd.DataFrame(np.arange(20).reshape(-1,5), columns=list("abcde"))
df[["a"]]

a
0   0
1   5
2  10
3  15

Problem 21

1 - In df, interchange columns 'a' and 'c'.

2 - Create a generic function to interchange two columns, without hardcoding column names.

3 - Sort the columns in reverse alphabetical order, that is colume 'e' first through column 'a' last.

Input

```

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
```

In [18]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

# Solution Q1
df[list('cbade')]

# Solution Q2 - No hard coding
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

df1 = switch_columns(df, 'a', 'c')

# Solution Q3
df[sorted(df.columns)]
# or
df.sort_index(axis=1, ascending=False, inplace=True)
df

e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

Problem 22

From df, filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

Input

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [35]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df = df.iloc[::20,:][["Manufacturer","Model","Type"]]
df

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

Problem 23 

Find the row position of the 5th largest value of column 'a' in df.

Input

```
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
```

In [3]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
print(df)
n = 5
df.a.argsort()[::-1][n]

    a   b   c
0  26   6  25
1   1  19  26
2  23   4  27
3  17   1  24
4  13   4  12
5  18   3  11
6  11   9  16
7  12  26  16
8   5  12   5
9   8  13  24


4

Problem 24 

In ser, find the position of the 2nd largest value greater than the mean.

Input
```
ser = pd.Series(np.random.randint(1, 100, 15))
```

In [15]:
ser = np.array(np.random.randint(1,100,15))
print("Ser ", np.array(ser), "Mean ", round(ser.mean()))

#ser.to_list()
#arr = np.arange(1,10)
np.argwhere(ser > 50)[1]

Ser  [37 82 76 95 16 50  5 59 26  6 84 79 42 12 32] Mean  47


array([2], dtype=int64)

In [16]:
ser = pd.Series(np.random.randint(1,100,15))
print("Ser ", np.array(ser), "Mean ", round(ser.mean()))

ser.to_list()
arr = np.arange(1,10)
#np.argwhere(ser > 50)

Ser  [13 12 17 34  9 77 98 73 36 11 40 10 27  9  1] Mean  31


Problem 25


Get one-hot encodings for column 'a' in the dataframe df and append it as columns.

Input

```
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
```
Output

```
   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24
```

In [14]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

# Solution
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


In [61]:
ser = np.array(np.random.randint(1,100,15))
print("Ser ", np.array(ser), "Mean ", round(ser.mean()))

#ser.to_list()
#arr = np.arange(1,10)
np.argwhere(ser > 50)[1]

Ser  [23 15 44 51 61  3 94 40  3 82 96 42 83 37 14] Mean  46


array([4], dtype=int64)

In [64]:
arr = np.array(np.random.randint(1,100,15))
print("arr ",arr, "mean",arr.mean())       #2,3,5,6,8,34,34,44,50,53,71,79,82,99,99

arr  [ 2  6 53 71 44 79 99 82  8 50  5 34  3 99 34] mean 44.6


In [67]:
output = np.argwhere(arr > arr.mean())
output

array([[ 2],
       [ 3],
       [ 5],
       [ 6],
       [ 7],
       [ 9],
       [13]], dtype=int64)

In [70]:
output = np.argwhere(arr > arr.mean())[1]
output

array([3], dtype=int64)

In [69]:
output

array([[ 2],
       [ 3],
       [ 5],
       [ 6],
       [ 7],
       [ 9],
       [13]], dtype=int64)

In [64]:
arr = np.array(np.random.randint(1,100,15))
print("arr ",arr, "mean ",arr.mean())
out = np.argwhere(arr > arr.mean())

arr  [63 36 96 10 82 98 34  1 45 69 29 48 95 23  1] mean  48.666666666666664


In [65]:
out

array([[ 0],
       [ 2],
       [ 4],
       [ 5],
       [ 9],
       [12]], dtype=int64)

In [69]:
out[2]

array([4], dtype=int64)